apiVersion: v1
kind: Secret
metadata:
  name: credentials
type: Opaque
data:
  VOLTALIS_USERNAME: {{index . "voltalis_username" | b64enc}}
  VOLTALIS_PASSWORD: {{index . "voltalis_password" | b64enc}}
