apiVersion: v1
kind: Service
metadata:
  name: voltalisrelay
  namespace: voltalisrelay
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: voltalisrelay
  type: ClusterIP
